### ISSUE TITLE
AStar

### ISSUE THREAD

**Issue by Schniz** [Schniz/robotikka#2]

**Comment by tomBold** [comment]
kaka

**Comment by Schniz** [comment]
את קקהההההה

אבל תמונה ממש יפה

**Comment by tomBold** [comment]
תודה חיים

**Comment by Schniz** [comment]
looks like I'm done with the AStar for now :star: :star2: :dizzy: :stars:

**Comment by tomBold** [comment]
checked?

**Comment by Schniz** [comment]
Nothing's really checked.

**Comment by tomBold** [comment]
Nothing really works for now
